#! /usr/bin/ruby

require "helper"

class TC_Povray_Element < Test::Unit::TestCase

  CPE = CrystalCell::Povray::Element

  def setup
  end

  def test_radius
    assert_equal(0.2  , CPE.radius(1    ))
    assert_equal(1.22 , CPE.radius(2    ))
    assert_equal(0.59 , CPE.radius(3    ))
    assert_equal(0.27 , CPE.radius(4    ))
    assert_equal(0.11 , CPE.radius(5    ))
    assert_equal(0.15 , CPE.radius(6    ))
    assert_equal(1.46 , CPE.radius(7    ))
    assert_equal(1.4  , CPE.radius(8    ))
    assert_equal(1.33 , CPE.radius(9    ))
    assert_equal(1.6  , CPE.radius(10   ))
    assert_equal(1.02 , CPE.radius(11   ))
    assert_equal(0.72 , CPE.radius(12   ))
    assert_equal(0.39 , CPE.radius(13   ))
    assert_equal(0.26 , CPE.radius(14   ))
    assert_equal(0.17 , CPE.radius(15   ))
    assert_equal(1.84 , CPE.radius(16   ))
    assert_equal(1.81 , CPE.radius(17   ))
    assert_equal(1.92 , CPE.radius(18   ))
    assert_equal(1.51 , CPE.radius(19   ))
    assert_equal(1.12 , CPE.radius(20   ))
    assert_equal(0.745, CPE.radius(21   ))
    assert_equal(0.605, CPE.radius(22   ))
    assert_equal(0.58 , CPE.radius(23   ))
    assert_equal(0.615, CPE.radius(24   ))
    assert_equal(0.83 , CPE.radius(25   ))
    assert_equal(0.78 , CPE.radius(26   ))
    assert_equal(0.745, CPE.radius(27   ))
    assert_equal(0.69 , CPE.radius(28   ))
    assert_equal(0.73 , CPE.radius(29   ))
    assert_equal(0.74 , CPE.radius(30   ))
    assert_equal(0.62 , CPE.radius(31   ))
    assert_equal(0.53 , CPE.radius(32   ))
    assert_equal(0.335, CPE.radius(33   ))
    assert_equal(1.98 , CPE.radius(34   ))
    assert_equal(1.96 , CPE.radius(35   ))
    assert_equal(1.98 , CPE.radius(36   ))
    assert_equal(1.61 , CPE.radius(37   ))
    assert_equal(1.26 , CPE.radius(38   ))
    assert_equal(1.019, CPE.radius(39   ))
    assert_equal(0.72 , CPE.radius(40   ))
    assert_equal(0.64 , CPE.radius(41   ))
    assert_equal(0.59 , CPE.radius(42   ))
    assert_equal(0.56 , CPE.radius(43   ))
    assert_equal(0.62 , CPE.radius(44   ))
    assert_equal(0.665, CPE.radius(45   ))
    assert_equal(0.86 , CPE.radius(46   ))
    assert_equal(1.15 , CPE.radius(47   ))
    assert_equal(0.95 , CPE.radius(48   ))
    assert_equal(0.8  , CPE.radius(49   ))
    assert_equal(0.69 , CPE.radius(50   ))
    assert_equal(0.76 , CPE.radius(51   ))
    assert_equal(2.21 , CPE.radius(52   ))
    assert_equal(2.2  , CPE.radius(53   ))
    assert_equal(0.48 , CPE.radius(54   ))
    assert_equal(1.74 , CPE.radius(55   ))
    assert_equal(1.42 , CPE.radius(56   ))
    assert_equal(1.16 , CPE.radius(57   ))
    assert_equal(0.97 , CPE.radius(58   ))
    assert_equal(1.126, CPE.radius(59   ))
    assert_equal(1.109, CPE.radius(60   ))
    assert_equal(1.093, CPE.radius(61   ))
    assert_equal(1.27 , CPE.radius(62   ))
    assert_equal(1.066, CPE.radius(63   ))
    assert_equal(1.053, CPE.radius(64   ))
    assert_equal(1.04 , CPE.radius(65   ))
    assert_equal(1.027, CPE.radius(66   ))
    assert_equal(1.015, CPE.radius(67   ))
    assert_equal(1.004, CPE.radius(68   ))
    assert_equal(0.994, CPE.radius(69   ))
    assert_equal(0.985, CPE.radius(70   ))
    assert_equal(0.977, CPE.radius(71   ))
    assert_equal(0.71 , CPE.radius(72   ))
    assert_equal(0.64 , CPE.radius(73   ))
    assert_equal(0.6  , CPE.radius(74   ))
    assert_equal(0.53 , CPE.radius(75   ))
    assert_equal(0.63 , CPE.radius(76   ))
    assert_equal(0.625, CPE.radius(77   ))
    assert_equal(0.625, CPE.radius(78   ))
    assert_equal(1.37 , CPE.radius(79   ))
    assert_equal(1.02 , CPE.radius(80   ))
    assert_equal(0.885, CPE.radius(81   ))
    assert_equal(1.19 , CPE.radius(82   ))
    assert_equal(1.03 , CPE.radius(83   ))
    assert_equal(0.94 , CPE.radius(84   ))
    assert_equal(0.62 , CPE.radius(85   ))
    assert_equal(0.8  , CPE.radius(86   ))
    assert_equal(1.8  , CPE.radius(87   ))
    assert_equal(1.48 , CPE.radius(88   ))
    assert_equal(1.12 , CPE.radius(89   ))
    assert_equal(1.05 , CPE.radius(90   ))
    assert_equal(0.78 , CPE.radius(91   ))
    assert_equal(0.73 , CPE.radius(92   ))
    assert_equal(0.75 , CPE.radius(93   ))
    assert_equal(0.86 , CPE.radius(94   ))
    assert_equal(0.975, CPE.radius(95   ))
    assert_equal(0.8  , CPE.radius(96   ))
    assert_equal(0.8  , CPE.radius(97   ))
    assert_equal(0.8  , CPE.radius(98   ))
    assert_equal(0.8  , CPE.radius(99   ))
    assert_equal(0.8  , CPE.radius(100  ))
    assert_equal(0.8  , CPE.radius(101  ))
    assert_equal(0.8  , CPE.radius(102  ))
    assert_equal(0.8  , CPE.radius(103  ))

    assert_equal(0.2  , CPE.radius( 'H'  ))
    assert_equal(1.22 , CPE.radius( 'He' ))
    assert_equal(0.59 , CPE.radius( 'Li' ))
    assert_equal(0.27 , CPE.radius( 'Be' ))
    assert_equal(0.11 , CPE.radius( 'B'  ))
    assert_equal(0.15 , CPE.radius( 'C'  ))
    assert_equal(1.46 , CPE.radius( 'N'  ))
    assert_equal(1.4  , CPE.radius( 'O'  ))
    assert_equal(1.33 , CPE.radius( 'F'  ))
    assert_equal(1.6  , CPE.radius( 'Ne' ))
    assert_equal(1.02 , CPE.radius( 'Na' ))
    assert_equal(0.72 , CPE.radius( 'Mg' ))
    assert_equal(0.39 , CPE.radius( 'Al' ))
    assert_equal(0.26 , CPE.radius( 'Si' ))
    assert_equal(0.17 , CPE.radius( 'P'  ))
    assert_equal(1.84 , CPE.radius( 'S'  ))
    assert_equal(1.81 , CPE.radius( 'Cl' ))
    assert_equal(1.92 , CPE.radius( 'Ar' ))
    assert_equal(1.51 , CPE.radius( 'K'  ))
    assert_equal(1.12 , CPE.radius( 'Ca' ))
    assert_equal(0.745, CPE.radius( 'Sc' ))
    assert_equal(0.605, CPE.radius( 'Ti' ))
    assert_equal(0.58 , CPE.radius( 'V'  ))
    assert_equal(0.615, CPE.radius( 'Cr' ))
    assert_equal(0.83 , CPE.radius( 'Mn' ))
    assert_equal(0.78 , CPE.radius( 'Fe' ))
    assert_equal(0.745, CPE.radius( 'Co' ))
    assert_equal(0.69 , CPE.radius( 'Ni' ))
    assert_equal(0.73 , CPE.radius( 'Cu' ))
    assert_equal(0.74 , CPE.radius( 'Zn' ))
    assert_equal(0.62 , CPE.radius( 'Ga' ))
    assert_equal(0.53 , CPE.radius( 'Ge' ))
    assert_equal(0.335, CPE.radius( 'As' ))
    assert_equal(1.98 , CPE.radius( 'Se' ))
    assert_equal(1.96 , CPE.radius( 'Br' ))
    assert_equal(1.98 , CPE.radius( 'Kr' ))
    assert_equal(1.61 , CPE.radius( 'Rb' ))
    assert_equal(1.26 , CPE.radius( 'Sr' ))
    assert_equal(1.019, CPE.radius( 'Y'  ))
    assert_equal(0.72 , CPE.radius( 'Zr' ))
    assert_equal(0.64 , CPE.radius( 'Nb' ))
    assert_equal(0.59 , CPE.radius( 'Mo' ))
    assert_equal(0.56 , CPE.radius( 'Tc' ))
    assert_equal(0.62 , CPE.radius( 'Ru' ))
    assert_equal(0.665, CPE.radius( 'Rh' ))
    assert_equal(0.86 , CPE.radius( 'Pd' ))
    assert_equal(1.15 , CPE.radius( 'Ag' ))
    assert_equal(0.95 , CPE.radius( 'Cd' ))
    assert_equal(0.8  , CPE.radius( 'In' ))
    assert_equal(0.69 , CPE.radius( 'Sn' ))
    assert_equal(0.76 , CPE.radius( 'Sb' ))
    assert_equal(2.21 , CPE.radius( 'Te' ))
    assert_equal(2.2  , CPE.radius( 'I'  ))
    assert_equal(0.48 , CPE.radius( 'Xe' ))
    assert_equal(1.74 , CPE.radius( 'Cs' ))
    assert_equal(1.42 , CPE.radius( 'Ba' ))
    assert_equal(0.71 , CPE.radius( 'Hf' ))
    assert_equal(0.64 , CPE.radius( 'Ta' ))
    assert_equal(0.6  , CPE.radius( 'W'  ))
    assert_equal(0.53 , CPE.radius( 'Re' ))
    assert_equal(0.63 , CPE.radius( 'Os' ))
    assert_equal(0.625, CPE.radius( 'Ir' ))
    assert_equal(0.625, CPE.radius( 'Pt' ))
    assert_equal(1.37 , CPE.radius( 'Au' ))
    assert_equal(1.02 , CPE.radius( 'Hg' ))
    assert_equal(0.885, CPE.radius( 'Tl' ))
    assert_equal(1.19 , CPE.radius( 'Pb' ))
    assert_equal(1.03 , CPE.radius( 'Bi' ))
    assert_equal(0.94 , CPE.radius( 'Po' ))
    assert_equal(0.62 , CPE.radius( 'At' ))
    assert_equal(0.8  , CPE.radius( 'Rn' ))
    assert_equal(1.8  , CPE.radius( 'Fr' ))
    assert_equal(1.48 , CPE.radius( 'Ra' ))
    assert_equal(1.16 , CPE.radius( 'La' ))
    assert_equal(0.97 , CPE.radius( 'Ce' ))
    assert_equal(1.126, CPE.radius( 'Pr' ))
    assert_equal(1.109, CPE.radius( 'Nd' ))
    assert_equal(1.093, CPE.radius( 'Pm' ))
    assert_equal(1.27 , CPE.radius( 'Sm' ))
    assert_equal(1.066, CPE.radius( 'Eu' ))
    assert_equal(1.053, CPE.radius( 'Gd' ))
    assert_equal(1.04 , CPE.radius( 'Tb' ))
    assert_equal(1.027, CPE.radius( 'Dy' ))
    assert_equal(1.015, CPE.radius( 'Ho' ))
    assert_equal(1.004, CPE.radius( 'Er' ))
    assert_equal(0.994, CPE.radius( 'Tm' ))
    assert_equal(0.985, CPE.radius( 'Yb' ))
    assert_equal(0.977, CPE.radius( 'Lu' ))
    assert_equal(1.12 , CPE.radius( 'Ac' ))
    assert_equal(1.05 , CPE.radius( 'Th' ))
    assert_equal(0.78 , CPE.radius( 'Pa' ))
    assert_equal(0.73 , CPE.radius( 'U'  ))
    assert_equal(0.75 , CPE.radius( 'Np' ))
    assert_equal(0.86 , CPE.radius( 'Pu' ))
    assert_equal(0.975, CPE.radius( 'Am' ))
    assert_equal(0.8  , CPE.radius( 'Cm' ))
    assert_equal(0.8  , CPE.radius( 'Bk' ))
    assert_equal(0.8  , CPE.radius( 'Cf' ))
    assert_equal(0.8  , CPE.radius( 'Es' ))
    assert_equal(0.8  , CPE.radius( 'Fm' ))
    assert_equal(0.8  , CPE.radius( 'Md' ))
    assert_equal(0.8  , CPE.radius( 'No' ))
    assert_equal(0.8  , CPE.radius( 'Lr' ))

    assert_equal(0.2  , CPE.radius(1    ))
    assert_equal(1.22 , CPE.radius(2    ))
  end

  def test_color
    assert_equal( [ 1.00, 0.80, 0.80 ], CPE.color('H' ) )
    assert_equal( [ 1.00, 0.80, 0.80 ], CPE.color(1   ) )
  end
end

